version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./src/main/resources/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 13306:3306
